apiVersion: v1
kind: Service
metadata:
    name: souravkarmakarpipelinesjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - port: 8080 
    selector:
        app: souravkarmakarpipelinesjavascriptdocker